
steps:
- name: 'gcr.io/cloud-builders/gcloud'
 args:
 — functions
 — deploy
 — — runtime=nodejs12
 — — trigger-http
 — — source=.js/ # Function source files
 — — entry-point=helloGET # Function entry point
 — helloGET # Function name

